// <auto-generated />
namespace OnlineShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedpgbrands : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedpgbrands));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231327541_updated-pgbrands"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
