// <auto-generated />
namespace OnlineShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedaddressandphonetoinvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedaddressandphonetoinvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "202012121257011_Added-address-and-phone-to-invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
