// <auto-generated />
namespace OnlineShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedinvoicerelatedtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedinvoicerelatedtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202012121034378_Added-invoice-related-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
